# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-04 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20201204_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employees_id',
            new_name='employee_id',
        ),
    ]
